[platformio]
src_dir = src/mouse_jiggler

[env:waveshare_rp2040_zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
framework = arduino
board_build.arduino.earlephilhower.usb_manufacturer = Logitech
board_build.arduino.earlephilhower.usb_product = Logitech USB Optical Mouse
board_build.arduino.earlephilhower.usb_vid = 0x046D
board_build.arduino.earlephilhower.usb_pid = 0xC077
build_flags =
    -DUSE_TINYUSB
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.15.2
