[platformio]
src_dir = src/mouse_jiggler

[env:waveshare_rp2040_zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
framework = arduino
build_flags =
    -DUSE_TINYUSB
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.15.2
